### ISSUE TITLE
Crash on iOS 10

### ISSUE THREAD

**Issue by sacredbanana** [emufreak/iAmiga#58] opened 2016-09-16 20:19 UTC
Pushing the settings button when opening the app on iPhone 6 Plus will cause the app to crash. Possibly an iOS 10 issue.

**Comment by emufreak** [comment] 2016-09-17 14:46
Can confirm this happens and is related to iOS 10

**Comment by emufreak** [comment] 2016-09-20 20:46
Fixed in iUAE 1.2.1

**Comment by sacredbanana** [comment] 2016-09-26 16:33
just downloaded 1.2.1 and the same thing happens

**Comment by emufreak** [comment] 2016-09-27 08:44
Where did you download it from? I made a mistake commiting 1.2.1 to the master branch

**Comment by emufreak** [comment] 2016-10-04 11:28
@simontoens @mithrendal @mrstargazer Can someone else test this. I have all my devices on iOS 9 due to jailbreak

**Comment by simontoens** [comment] 2016-10-04 11:51
I will have a look.

**Comment by simontoens** [comment] 2016-10-04 11:55
But I won't get to this right away as I am on vacation.

**Comment by sacredbanana** [comment] 2016-10-04 12:12
I downloaded it from the releases tab and also I pulled it from the master thread. Both crash on iOS 10 on my iPhone 6 Plus

**Comment by simontoens** [comment] 2016-10-05 01:32
@sacredbanana @emufreak I updated my iPad to iOS 10 - I cannot reproduce this.  I am running the latest code from the dev branch.

**Comment by sacredbanana** [comment] 2016-10-06 20:51
I can confirm the one on the dev branch is working fine.

**Comment by simontoens** [comment] 2016-10-06 23:44
Thanks for checking - @emufreak, maybe you can cut another release from the dev branch?

**Comment by simontoens** [comment] 2016-10-23 06:11
Sounds like we can close this?  @emufreak

**Closed as completed** 2017-03-27 19:22 UTC
